version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bookswap
      POSTGRES_PASSWORD: bookswap
      POSTGRES_DB: bookswapdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://bookswap:bookswap@db:5432/bookswapdb
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata: